### ISSUE TITLE
Implement enough of TSO and STACK closures to traverse heap

### ISSUE THREAD

**Issue by mpickering** [bgamari/ghc-debug#4]
The main GC roots are TSO closures but `ghc-heap` doesn't implement them yet. We need to implement enough of these two closures so that you can traverse them to access the meaty part of the heap.

**Comment by mpickering** [comment]
I have implemented enough of `TSO` closures to get access to the stack pointers. @bgamari said he would implement the `STACK` closure decoding at some point. However he wondered whether it should be implemented in `ghc-heap` because it is quite involved and might involve sufficient allocation to trigger a GC.

**Comment by bgamari** [comment]
I have started implementing stack support in https://github.com/bgamari/ghc-debug/tree/stack-walking.

Indeed I have essentially come to the conclusion that stack support is largely out of scope for `ghc-heap`. There are a few reasons for this:
 * `ghc-heap` primarily targets in-process heap traversal yet walking the stack of a running thread is in general unsafe
 * Unpacking a stack in one go requires a potentially large amount of allocation. Furthermore, because unpacking will require multiple allocations you need to be very careful while garbage collecting to ensure that all pieces of the partially-constructed result are visible to the GC and therefore scavenged.
 * A middle road that would be useful to `ghc-debug` would be to introduce a `Stack :: ByteArray# -> StgClosure` constructor to `ghc-heap`'s `StgClosure` type which would contain a verbatim copy of the closure. However, this would be only useful to stop-the-world users of `ghc-heap` since the array's contents would be invalid after the first GC.

Unfortunately I think this means that we will need to introduce our own closure type in `ghc-debug` .

#12  is another issue caused by `ghc-heap`'s lack of stack support.

**Comment by mpickering** [comment]
We can now fully traverse all the roots for a simple program.
